### ISSUE TITLE
The names of some languages are not displayed 

### ISSUE THREAD

**Issue by sivizius** [Dobiasd/programming-language-subreddits-and-their-choice-of-words#9]
In the first and interactive graphic, the labels for golang, objective-c and visual basic are missing

**Comment by Dobiasd** [comment]
Yeah, it's weird. In the source data, the labels are included normally:
- http://daiw.de/github/programming-language-subreddits-and-their-choice-of-words/mentions_chord_graph/subreddits.csv
- http://daiw.de/github/programming-language-subreddits-and-their-choice-of-words/mentions_chord_graph/matrix.json

But d3.js somewhat decides to now show them. I first thought it's because they are so small, but swift, which is even smaller compared to two of the three non-shown labels, is shown. `¯\_(ツ)_/¯`

![cS2no60](https://i.imgur.com/cS2no60.png)

But since this whole analysis is over half a decade old, and not updated or anything, I guess it's kind of ok to let it rot. :grin:

**Comment by sivizius** [comment]
What about a note in the text below?

**Comment by Dobiasd** [comment]
Like [so](https://github.com/Dobiasd/programming-language-subreddits-and-their-choice-of-words/commit/7202923dc9080717ce145225a1c36d05f72858aa)? :slightly_smiling_face:
